print('*** RECETA DE COCINA ***')
print('\n')
nombre_receta = (input("Ingrese nombre de la receta:"))
print('\n')
ingredientes = (input("Ingrese los ingredientes: "))
print('\n')
tiempo_preparacion = (input("Ingrese el tiempo de preparacion: "))
print('\n')
dificultad = (input("Ingrese dificiultad: "))
print('----------------------------')
print ('Nombre plato: ',{nombre_receta})
print('\n')
print('Ingredientes: ',{ingredientes})
print('\n')
print('Tiempo de preparacion: ',{tiempo_preparacion})
print('\n')
print('Dificultad: ',{dificultad})
